---
services:
  cs2-map-rcon-server:
    container_name: cs2-map-rcon-server
    build: .
    environment:
      PORT: 16969
      #DEBUG: true
      #WEB_PATH: /cs2/
      #TRUSTED_ORIGINS: https://homeassistant.example.com
    restart: unless-stopped
    network_mode: host
    secrets:
      - rcon_targets
secrets:
  rcon_targets:
    file: secrets/rcon_targets
